### ISSUE TITLE
cgroup ordering change causes errors

### ISSUE THREAD

**Issue by jkatz** [CrunchyData/pgnodemx#1]
Reported in CrunchyData/postgres-operator#2037:

```
$ cat /proc/self/cgroup:
...
6:cpuacct,cpu:/kubepods.slice/...
...
```

vs.

```
$ ls -l /sys/fs/cgroup/ :
lrwxrwxrwx 1 root root 11 Nov 23 09:23 cpu -> cpu,cpuacct
lrwxrwxrwx 1 root root 11 Nov 23 09:23 cpuacct -> cpu,cpuacct
drwxr-xr-x 2 root root 0 Nov 23 09:23 cpu,cpuacct
```

The change in ordering causes pgnodemx to fail to grab particularly metrics. In the Postgres Operator, this manifests as the inability to scrape these metrics and make them available in the crunchy-postgres-exporter.

**Comment by jconway** [comment]
Fixed in 1.0.2
