### ISSUE TITLE
SELECT monitor.fsinfo('/pgdata'); fails to complete due to: DETAIL:  Expected numeric, got bigint

### ISSUE THREAD

**Issue by sharkymcdongles** [CrunchyData/pgnodemx#12]
**Describe the issue:**
```
postgres=# SELECT monitor.fsinfo('/pgdata');
ERROR:  query-specified return tuple and function return type are not compatible
DETAIL:  Expected numeric, got bigint
```

**Describe the expected behavior:**
This to complete without error.

**Tell us about your environment:**  
- pgMonitor version:  N/A
- Container or non-container:  container
- Container name / image:  registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0
- Operating System for non-container:  N/A
- PostgreSQL Version:  13.5
- Exporter(s) in use (incl. version):  registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0
- Prometheus version:  N/A
- AlertManager version:  N/A
- Grafana version:  N/A
- pgnodemx version: pgnodemx13-1.2.0-0Crunchy.el8.centos.x86_64

**Comment by keithf4** [comment]
I don't have a CentOS8 system available to test at this time, but I set up PG13.5 with version 1.2 on RHEL8 and so far have not been able to reproduce this error. Note this isn't in a container environment, so I may have to contact that team to see if they can look further there.
```
postgres=# \dx
List of installed extensions
-[ RECORD 2 ]-----------------------------------------------------------------------
Name        | pgnodemx
Version     | 1.2
Schema      | monitor
Description | SQL functions that allow capture of node OS metrics from PostgreSQL

postgres=# select * from monitor.fsinfo('/var/lib/pgsql/13/echo/data');
-[ RECORD 1 ]----+------------
major_number     | 253
minor_number     | 0
type             | xfs
block_size       | 4096
blocks           | 4452864
total_bytes      | 18238930944
free_blocks      | 3626762
free_bytes       | 14855217152
available_blocks | 3626762
available_bytes  | 14855217152
total_file_nodes | 8910848
free_file_nodes  | 8849006
mount_flags      | relatime
```
Just to note, we are also no longer supporting CentOS8 at this time, so 1.2 is the last version of pgnodemx that has been built in our repository. Version 1.3 is the latest and a new version will be released soon to support PG15. This also means that if a bug is found around this issue, a new package will not be created for CentOS8 that might contain any fixes. 

It looks like PGO 5.0.5 was the last version that supported CentOS8. Versions 5.1+ are all UBI8 with RHEL supplements. We would suggest trying to go to the latest devportal build of 5.2 with the latest version of pgnodemx and see if the issue still persists.

**Comment by cbandy** [comment]
> ```
> ERROR:  query-specified return tuple and function return type are not compatible
> DETAIL:  Expected numeric, got bigint
> ```

This sounds like the extension has not been updated. https://github.com/CrunchyData/postgres-operator/issues/2965 discusses workarounds and was fixed recently.

**Comment by sharkymcdongles** [comment]
> > ```
> > ERROR:  query-specified return tuple and function return type are not compatible
> > DETAIL:  Expected numeric, got bigint
> > ```
> 
> This sounds like the extension has not been updated. [CrunchyData/postgres-operator#2965](https://github.com/CrunchyData/postgres-operator/issues/2965) discusses workarounds and was fixed recently.

Thanks this was the problem! Awesome! <3
