### ISSUE TITLE
Build a rpm package for pgnodemx

### ISSUE THREAD

**Issue by Eric-zch** [CrunchyData/pgnodemx#14]
Hi There,
Since pgnodemx is a popular extension for PostgreSQL users, is it possible to provide it as a rpm package from Postgre Repo like https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-8-x86_64/ 

Thank you.

**Comment by keithf4** [comment]
We do not maintain any packages for this extension in that repository at this time. Feel free to send a message to the yum packaging mailing list to see if someone there that has access to the PGDG repository might be able to maintain it

https://www.postgresql.org/list/pgsql-pkg-yum/
https://www.postgresql.org/list/

**Comment by Eric-zch** [comment]
@keithf4 
Hi Keith, I will send a message to yum packaging mailing list, thank you.
