### ISSUE TITLE
The 1.5 release fails to build on PG16

### ISSUE THREAD

**Issue by crunchyheath** [CrunchyData/pgnodemx#17]
When trying to compile the 1.5 release with PG16 I get the following compiler error:

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -fvisibility=hidden -I/usr/pgsql-16/include -I. -I./ -I/usr/pgsql-16/include/server -I/usr/pgsql-16/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -DGIT_HASH=\"1.5\"  -c -o pgnodemx.o pgnodemx.c
In file included from pgnodemx.c:60:
genutils.h:41:31: error: conflicting types for ‘find_option’
 extern struct config_generic *find_option(const char *name);

I was able to compile it fine for PG11 through PG15 on multiple different operating systems, but I get this same failure trying to compile with PG16 on every operating system.

**Comment by cbandy** [comment]
Postgres started exporting its own `find_option` in this commit: https://github.com/postgres/postgres/commit/0a20ff54f5e66158930d5328f89f087d4e9ab400

**Comment by keithf4** [comment]
@cbandy you see any reason we can't use the built in version and drop the one defined in pgnodemx?

**Comment by keithf4** [comment]
Doing that just to test things, now getting 
```parseutils.c: In function ‘get_double_from_file’:
parseutils.c:599:26: error: too few arguments to function ‘float8in_internal’
  599 |                 result = float8in_internal(rawstr, NULL, "double precision", rawstr);
      |                          ^~~~~~~~~~~~~~~~~
In file included from parseutils.c:39:
/opt/pgsql16b2/include/server/utils/float.h:44:15: note: declared here
   44 | extern float8 float8in_internal(char *num, char **endptr_p,
      |               ^~~~~~~~~~~~~~~~~
make: *** [<builtin>: parseutils.o] Error 1
```
So seems PG16 may have started building things in that pgnodemx was trying to do itself?

**Comment by youattd** [comment]
Looks like Joe copied internal pg functions and made static copies in the extension source file `parseutils.c`.  He defined them as `static` so they're local/private to that file, but that file also included a pg internal include file that changed in pg16:   `src/include/utils/float.h`

In pg 16, the signature / declaration changed for `float8in_internal`.  One of the extension functions that he copied is `float8in_internal`.

In pg 16 it needs one more arg.  Comparing 15.3 source with 16_beta2 source, note the extra arg in `src/include/utils/float.h` which is also included by the extension source ( note the extra arg `struct Node *escontext` in the pg16 signature)
 
```
diff /tmp/rel153-float.h /tmp/rel16b2-float.h

< extern float8 float8in_internal(char *num, char **endptr_p, const char *type_name, const char *orig_string);
< extern float8 float8in_internal_opt_error(char *num, char **endptr_p, const char *type_name, const char *orig_string, bool *have_error);
---
> extern float8 float8in_internal(char *num, char **endptr_p, const char *type_name, const char *orig_string, struct Node *escontext);
> extern float4 float4in_internal(char *num, char **endptr_p, const char *type_name, const char *orig_string, struct Node *escontext);
```

So it may work to update the extension's static definition of the function to add the new arg, but it may need new handling as well in the extension's copied function.  Safer to compare the extension's copy with the new pg16 implementation and if needed, patch the extensions copy with changes from pg16, with appropriate `#ifdef pg version`.  Or better, review the extension's copy and see if it can use the pg internal implementation.

Also it looks like `float8in_internal_opt_error`, that he copied for the extension no longer has a declaration in pg16.  That may be ok, or it may be the next compile error to deal with.

pg source file is here:  `./src/backend/utils/adt/float.c`

**Comment by keithf4** [comment]
Yeah I was looking to see if I could just replace them to use the internal pg functions instead. Unless you can see why that was done that way and it should stay like that?

**Comment by youattd** [comment]
Worth a diff of the copied (and modified?) extension source for `float8in_internal` in `parseutils.c` with the pg15 source in `src/backend/utils/adt/float.c` to see what he changed.

Also looks like pg16 refactored `float8in_internal_opt_error` and `float8in_internal` to include the former inline in the latter.  So the new source has diverged more from the extension copy.

**Comment by keithf4** [comment]
Couldn't see a clean way of having older versions of PG use the upstream `find_option` since it wasn't in any header files. Just put version conditionals around custom made ones and set it so PG16+ use upstream. Can test that things work as expected on 16 from there.
