### ISSUE TITLE
ccp_nodemx_data_disk pq: value "18446744073709551615" is out of range for type bigint

### ISSUE THREAD

**Issue by douggutaby** [CrunchyData/pgnodemx#3]
Hi,

We have an OpenShift cluster with CrunchyData postgres-operator with enabled prometheus metrics. In the export container we have found the following error:
time="2021-09-20T07:27:57Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_data_disk pq: value \"18446744073709551615\" is out of range for type bigint" source="postgres_exporter.go:1356"

I found that the monitor.fsinfo() function provides this data. For fsinfo('/') I got proper data, but for fsinfo('/pgdata') I got the number is too big for bigint like above.
We use rook-ceph for persistent volumes. Probably ceph cannot provide this data or reach a limit, maybe selinux didn't allow to collect something. Please help me what is wrong here.

## Environment

- Platform: OpenShift
- Platform Version: 4.7.0
- PGO Image Tag: centos8-12.8-4.7.2
- Postgres Version: 12
- Storage: rook-ceph

### REPRO

Create cluster with metrics enabled.

### EXPECTED

No error, metrics collection.

### ACTUAL

ccp_nodemx_data_disk pq: value "18446744073709551615" is out of range for type bigint

## Additional Information

Recently we upgraded our postgres operator from 4.5.1 to 4.7.2 but I found the same in the old logs as well.

**Comment by jconway** [comment]
Sorry for the delay, but we will have a fix committed and new release out shortly.

**Comment by douggutaby** [comment]
> Sorry for the delay, but we will have a fix committed and new release out shortly.

Thank you for your response. What does shortly mean? :) Days, weeks, ...

**Comment by douggutaby** [comment]
Thank you @pgguru. Can you tell me when it will be in the postgres operator? Will I find it in the next release?

**Comment by jkatz** [comment]
@douggutaby The folks who work on pgnodemx are independent from those on the Postgres Operator. They do not know when it will be released in that project.

For PGO releases, information is shared on the mailing list, which can be found here: https://access.crunchydata.com/documentation/postgres-operator/v5/support/
